import Head from "next/head";
import Navbar from "../components/Dashboard/Navbar";
import Products from "../components/Dashboard/Products";
import Searchbar from "../components/Dashboard/Searchbar";
import withLayout from '../components/HOC/withLayout'
import HeaderandSidenav from "../layouts/HeaderandSidenav";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Bildemp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Products/>
      {/* <Searchbar/> */}
    </div>
  );
}
//  withLayout(Home, HeaderandSidenav)